const PERMISSIONS = {
  // TODO RELATED
    READ_OWN_TODOS: 'READ_OWN_TODOS',
    CREATE_TODO: 'CREATE_TODO',
    UPDATE_OWN_TODO: 'UPDATE_OWN_TODO',
    DELETE_OWN_TODO: 'DELETE_OWN_TODO',
    READ_ALL_TODOS: 'READ_ALL_TODOS',
    READ_ANY_TODO: 'READ_ANY_TODO',
    UPDATE_ANY_TODO: 'UPDATE_ANY_TODO',
    DELETE_ANY_TODO: 'DELETE_ANY_TODO',
  
// SUBTODO RELATED

    FETCH_ALL_SUBTODOS:'FETCH_ALL_SUBTODOS',
    CREATE_SUBTODOS:'CREATE_SUBTODOS',
    DELETE_OWN_SUBTODO:'DELETE_OWN_SUBTODO',
    UPDATE_OWN_SUBTODO:'UPDATE_OWN_SUBTODO',
    FETCH_OWN_SUBTODOS:'FETCH_OWN_SUBTODOS',
// USER RELATED
    READ_ALL_USERS: 'READ_ALL_USERS',
    READ_ANY_USER: 'READ_ANY_USER',
    CREATE_ANY_USER: 'CREATE_ANY_USER', 
    UPDATE_ANY_USER: 'UPDATE_ANY_USER',
    DELETE_ANY_USER: 'DELETE_ANY_USER',
    UPDATE_OWN_PROFILE: 'UPDATE_OWN_PROFILE',


    // NOTIFICATION RELATED
    CREATE_OWN_NOTIFICATION:'CREATE_OWN_NOTIFICATION',
    CREATE_ANY_NOTIFICATION: 'CREATE_ANY_NOTIFICATION',
    READ_NOTIFICATIONS: 'READ_NOTIFICATIONS',
    MARK_NOTIFICATION_READ: 'MARK_NOTIFICATION_READ',
  };
  
  const ROLES = {
    USER: 'user',
    ADMIN: 'admin',
  };
  
  const rolePermissions = {
    [ROLES.USER]: [
      PERMISSIONS.READ_OWN_TODOS,
      PERMISSIONS.CREATE_TODO,
      PERMISSIONS.UPDATE_OWN_TODO,
      PERMISSIONS.DELETE_OWN_TODO,
      PERMISSIONS.MARK_NOTIFICATION_READ,
      PERMISSIONS.UPDATE_OWN_PROFILE,
      PERMISSIONS.READ_ANY_TODO, 
      PERMISSIONS.READ_ANY_USER,// Allow users to see basic info of other users (e.g., for mentions/assignments)
      PERMISSIONS.CREATE_OWN_NOTIFICATION ,
      PERMISSIONS.READ_NOTIFICATIONS,
      PERMISSIONS.CREATE_SUBTODOS,
      PERMISSIONS.FETCH_OWN_SUBTODOS,
      PERMISSIONS.UPDATE_OWN_SUBTODO,
      PERMISSIONS.DELETE_OWN_SUBTODO
    ],
    [ROLES.ADMIN]: [
      // Admins inherit all user permissions
      ...Object.values(PERMISSIONS), 
    ],
  };
  
  module.exports = {
    PERMISSIONS,
    ROLES,
    rolePermissions,
  };